# Enable Hardware Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Enable Mouse Cursor Processing Subsystem
CONFIG_ZMK_POINTING=y

# Global Debounce Setup for Direct Pin Switches
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
