# Enable Encoder Support
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_OWN_THREAD=y

# Enable the updated ZMK Pointing engine (Required for modern scroll wheel emulation)
CONFIG_ZMK_POINTING=y

# Enable ZMK Studio Support
CONFIG_ZMK_STUDIO=y
