# Enable Encoder Support
CONFIG_EC11=y
# Dedicated high-priority thread prevents missing rapid high-res pulses
CONFIG_EC11_TRIGGER_OWN_THREAD=y

# Enable Mouse Emulation Features (Required for Scroll Wheel)
CONFIG_ZMK_MOUSE=y

# Enable ZMK Studio Support
CONFIG_ZMK_STUDIO=y