# Enable Encoder Support
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Enable Mouse Emulation Features (Required for Scroll Wheel)
CONFIG_ZMK_MOUSE=y

# Enable ZMK Studio Support
CONFIG_ZMK_STUDIO=y
